easy_admin:
    site_name: 'Ultimate Blog'
    design:
        menu:
            - label: 'Users'
              children: ['User']
            - label: 'Comments'
              children: ['Comment']
            - label: 'Posts'
              children: ['Post']

    entities:
       # List the entity class name you want to manage
        User:
            class: App\Entity\User
            list:
                title: 'Users'
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'add' }
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }

        Comment:
            class: App\Entity\Comment
            list:
                title: 'Comments'
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'add' }
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }

        Post:
            class: App\Entity\Post
            list:
                title: 'Posts'
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'add' }
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }